name: Backend CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/backend/**'

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 1. Di chuyển vào thư mục code trên Server
            # (Thay đổi đường dẫn này theo đúng thực tế trên server của bạn)
            cd Auto-Translating-Manga-Website/src/backend

            pm2 stop "backend" || true
            
            # 2. Lấy code mới nhất về
            git pull origin main
            
            # 3. Cài đặt các gói thư viện mới (nếu có update trong package.json)
            # Rất quan trọng vì dev mode đọc trực tiếp từ node_modules
            sudo npm install
            
            # 4. Khởi động lại tiến trình PM2
            # Lệnh này sẽ restart process có tên là "frontend" để nó chạy lại code mới
            sudo pm2 restart "backend" --update-env